"use client";

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import type { ProcessInputs, DerivedParameters, RiskScore, Confidence } from "@/lib/types";
import type { PartialAssessmentResult } from "@/lib/engine";
import {
  RISK_COLOURS,
  METABOLIC_HEAT_FACTOR,
  RUSZKOWSKI_CONSTANT,
  RHO,
  FEED_TAU_MAP,
  KLA_CO2_O2_RATIO,
  H_CO2,
  G,
  ATMOSPHERIC_PRESSURE_PA,
  RQ_DEFAULTS,
  CO2_BIOMASS_THRESHOLD,
  CO2_OUR_THRESHOLD,
  VANT_RIET_COALESCING_COEFFICIENT,
  VANT_RIET_COALESCING_PV_EXPONENT,
  VANT_RIET_COALESCING_VS_EXPONENT,
} from "@/lib/constants";
import { deriveVesselGeometry, deriveGasVelocity } from "@/lib/engine";

// --- Constants ---

const NAVY = "#1B3A5C";
const TEAL = "#0D7377";
const FOOTER_TEXT =
  "Generated by Lemnisca Fermentation Scale-Up Risk Predictor \u2014 lemnisca.com";

const SPECIES_LABELS: Record<string, string> = {
  e_coli: "E. coli",
  b_subtilis: "B. subtilis",
  s_cerevisiae: "S. cerevisiae",
  p_pastoris: "P. pastoris",
  other_bacteria: "Other bacterium",
  other_yeast: "Other yeast",
};

const PROCESS_TYPE_LABELS: Record<string, string> = {
  batch: "Batch",
  fed_batch: "Fed-batch",
};

const DOMAIN_LABELS: Record<string, string> = {
  otr: "Oxygen Transfer (OTR)",
  mixing: "Mixing",
  shear: "Shear Stress",
  co2: "CO\u2082 Accumulation",
  heat: "Heat Removal",
};

// --- Helpers ---

function fmt(n: number, decimals = 1): string {
  return n.toFixed(decimals);
}

function fmtInt(n: number): string {
  return Math.round(n).toString();
}

function riskLabel(score: RiskScore): string {
  return score.charAt(0).toUpperCase() + score.slice(1);
}

function confidenceLabel(c: Confidence): string {
  switch (c) {
    case "high_confidence":
      return "High-confidence";
    case "reliable":
      return "Reliable";
    case "directional":
      return "Directional";
  }
}

function klaVantRiet(pv: number, vs: number): number {
  const kla_s =
    VANT_RIET_COALESCING_COEFFICIENT *
    Math.pow(pv, VANT_RIET_COALESCING_PV_EXPONENT) *
    Math.pow(vs, VANT_RIET_COALESCING_VS_EXPONENT);
  return kla_s * 3600;
}

function pilotVolume(vLab: number, vTarget: number): number {
  return Math.sqrt(vLab * vTarget);
}

function countEstimatedParams(inputs: ProcessInputs): {
  provided: number;
  estimated: number;
  total: number;
} {
  let provided = 0;
  let estimated = 0;

  // Always provided
  const alwaysProvided: (keyof ProcessInputs)[] = [
    "organism_class",
    "organism_species",
    "process_type",
    "v_lab",
    "v_target",
    "rpm",
    "biomass",
  ];
  provided += alwaysProvided.length;

  // Conditionally provided vs estimated
  if (inputs.our_mode === "measured" && inputs.our_measured != null) {
    provided += 1;
  } else if (inputs.our_mode === "exhaust_gas") {
    provided += 1;
  } else {
    estimated += 1; // OUR estimated from literature
  }

  // Optional params that have defaults
  const optionalWithDefaults: { key: keyof ProcessInputs; defaultCheck: boolean }[] = [
    { key: "h_d_lab", defaultCheck: inputs.h_d_lab === 1.2 },
    { key: "h_d_target", defaultCheck: false },
    { key: "n_impellers", defaultCheck: false },
    { key: "impeller_type", defaultCheck: inputs.impeller_type === "rushton" },
    { key: "vvm", defaultCheck: inputs.vvm === 1.0 },
    { key: "do_setpoint", defaultCheck: inputs.do_setpoint === 30 },
    { key: "temperature", defaultCheck: false },
    { key: "t_cw_inlet", defaultCheck: inputs.t_cw_inlet === 12 },
  ];

  for (const p of optionalWithDefaults) {
    provided += 1; // All are user-provided or defaulted
  }

  const total = provided + estimated;
  return { provided, estimated, total };
}

function getHighImpactAssumptions(
  inputs: ProcessInputs,
  derived: DerivedParameters,
  results: PartialAssessmentResult,
): string[] {
  const assumptions: string[] = [];

  if (inputs.our_mode === "estimate") {
    assumptions.push(
      `OUR estimated from literature midpoint for ${SPECIES_LABELS[inputs.organism_species] ?? inputs.organism_species}. ` +
        `Actual OUR may range from ${fmt(derived.our_min ?? 0)} to ${fmt(derived.our_max ?? 0)} mmol/L/h. ` +
        `Higher OUR increases OTR, heat, and CO\u2082 risk; lower OUR decreases them.`,
    );
  }

  assumptions.push(
    `Van\u2019t Riet coalescing correlation assumed. Non-coalescing media would yield ` +
      `higher kLa at the same P/V, reducing OTR risk.`,
  );

  if (inputs.impeller_type === "unknown") {
    assumptions.push(
      `Unknown impeller type defaulted to Rushton constants (Np = 5.0, Pg/P = 0.60). ` +
        `Actual power draw may differ, affecting all scale-up projections.`,
    );
  }

  return assumptions.slice(0, 3);
}

function getSingleMeasurementAdvice(inputs: ProcessInputs): string {
  if (inputs.our_mode === "estimate") {
    return "A direct OUR measurement at peak biomass would most improve this assessment.";
  }
  return "A kLa characterisation of the target vessel at operating conditions would most improve this assessment.";
}

// --- Mitigation text (reused from dashboard logic) ---

function getMitigation(
  domain: string,
  results: PartialAssessmentResult,
  inputs: ProcessInputs,
): string | null {
  const { otr, mixing, shear, co2, heat } = results;
  const score =
    domain === "otr" ? otr.score :
    domain === "mixing" ? mixing.score :
    domain === "shear" ? shear.score :
    domain === "co2" ? co2.score :
    heat.score;

  if (score !== "high" && score !== "critical") return null;

  switch (domain) {
    case "otr":
      return `Required kLa of ${fmt(otr.kla_required)} h\u207B\u00B9 exceeds standard P/V achievability at ${fmtInt(inputs.v_target)} L. Options: (1) Reduce target biomass ~20% to bring OUR within standard kLa range. (2) Dual Rushton or Rushton-to-PBT cascade configuration. (3) Pressure overlay (+0.5 bar increases C* by ~15%).`;
    case "mixing":
      if (mixing.da_max != null) {
        return `Mixing time at ${fmtInt(inputs.v_target)} L is ~${fmt(mixing.theta_mix_target)} s. Feed produces Da = ${fmt(mixing.da_max, 3)}. Options: (1) Switch to continuous feed. (2) Relocate feed port to impeller high-turbulence zone. (3) Reduce peak feed rate and extend feed duration.`;
      }
      return `Mixing time at ${fmtInt(inputs.v_target)} L is ~${fmt(mixing.theta_mix_target)} s. Options: (1) Add a second impeller. (2) Reduce target vessel H/D ratio. (3) Increase agitation speed within shear limits.`;
    case "shear":
      return `Tip speed of ${fmt(shear.tip_speed)} m/s at constant P/V exceeds ${SPECIES_LABELS[inputs.organism_species] ?? inputs.organism_species} threshold of ${fmt(shear.tip_speed_threshold)} m/s. Options: (1) Switch to pitched blade turbine. (2) Accept lower P/V with supplementary O\u2082 strategy. (3) Consider scale-up at constant tip speed instead of constant P/V.`;
    case "co2":
      return `Estimated pCO\u2082 at vessel bottom is ${fmt(co2.pco2_bottom ?? 0, 2)} bar. Options: (1) Increase sparging rate to enhance CO\u2082 stripping. (2) Reduce biomass target. (3) Lower H/D vessel geometry.`;
    case "heat":
      return `Metabolic heat generation of ${fmt(heat.q_metabolic)} kW exceeds jacket cooling capacity of ${fmt(heat.q_cool_max)} kW. Options: (1) Add internal cooling coil. (2) Reduce target biomass or OUR. (3) Lower process temperature if organism permits.`;
    default:
      return null;
  }
}

// --- Pilot computation (mirrors dashboard logic) ---

interface PilotRow {
  klaAchievable: number;
  mixingTime: number;
  da_max: number | null;
  tipSpeed: number;
  pco2Bottom: number | null;
  heatKwM3: number;
}

function computePilot(inputs: ProcessInputs, derived: DerivedParameters): PilotRow {
  const vPilot = pilotVolume(inputs.v_lab, inputs.v_target);
  const geometry = deriveVesselGeometry(vPilot, inputs.h_d_target, inputs.impeller_type, inputs.dt_ratio_target);
  const gas = deriveGasVelocity(inputs.vvm, vPilot, geometry.a_cross);

  const klaAchievable = klaVantRiet(derived.pv_lab, gas.vs);

  const pilotT = geometry.t_diameter;
  const pilotDimp = geometry.d_imp;
  const epsilon = derived.pv_lab / RHO;
  const mixingTime =
    RUSZKOWSKI_CONSTANT * pilotT * pilotT /
    (Math.pow(epsilon, 1 / 3) * Math.pow(pilotDimp, 4 / 3));

  let da_max: number | null = null;
  if (inputs.process_type === "fed_batch" && inputs.feed_frequency) {
    const tau = FEED_TAU_MAP[inputs.feed_frequency];
    da_max = mixingTime / tau;
  }

  const dImpLab = derived.lab_geometry.d_imp;
  const nTarget = derived.n_rps * Math.pow(dImpLab / pilotDimp, 5 / 3);
  const tipSpeed = Math.PI * nTarget * pilotDimp;

  let pco2Bottom: number | null = null;
  const activated =
    derived.biomass_cdw > CO2_BIOMASS_THRESHOLD || derived.our_peak > CO2_OUR_THRESHOLD;
  if (activated) {
    const rq =
      inputs.organism_species === "p_pastoris"
        ? RQ_DEFAULTS.p_pastoris_methanol
        : inputs.organism_species === "s_cerevisiae"
          ? RQ_DEFAULTS.s_cerevisiae_aerobic
          : RQ_DEFAULTS.bacteria_aerobic;
    const cer = rq * derived.our_peak;
    const klaO2Pilot = klaVantRiet(derived.pv_lab, gas.vs);
    const klaCo2 = KLA_CO2_O2_RATIO * klaO2Pilot;
    const pco2BulkAtm = (cer / 1000) / (klaCo2 * H_CO2);
    const pco2Bulk = pco2BulkAtm * 1.01325;
    const hLiquid = geometry.h_liquid;
    const dpHydro = RHO * G * hLiquid;
    pco2Bottom = pco2Bulk + (dpHydro / ATMOSPHERIC_PRESSURE_PA) * 1.01325;
  }

  const vPilotM3 = geometry.volume_m3;
  const qMetabolic = METABOLIC_HEAT_FACTOR * derived.our_peak * vPilotM3;
  const heatKwM3 = vPilotM3 > 0 ? qMetabolic / vPilotM3 : 0;

  return { klaAchievable, mixingTime, da_max, tipSpeed, pco2Bottom, heatKwM3 };
}

// --- Styles ---

const s = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 60,
    paddingHorizontal: 40,
    fontFamily: "Helvetica",
    fontSize: 9,
    color: "#333333",
  },
  footer: {
    position: "absolute",
    bottom: 25,
    left: 40,
    right: 40,
    fontSize: 7,
    color: "#999999",
    textAlign: "center",
  },
  // Header
  headerBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: NAVY,
    paddingBottom: 8,
    marginBottom: 16,
  },
  logoText: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    color: NAVY,
  },
  dateText: {
    fontSize: 8,
    color: "#666666",
  },
  // Section titles
  sectionTitle: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: NAVY,
    marginBottom: 8,
    marginTop: 12,
  },
  subsectionTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: TEAL,
    marginBottom: 4,
    marginTop: 8,
  },
  // Parameter summary box
  paramBox: {
    backgroundColor: "#F0F4F8",
    borderRadius: 4,
    padding: 10,
    marginBottom: 12,
  },
  paramRow: {
    flexDirection: "row",
    marginBottom: 2,
  },
  paramLabel: {
    width: 120,
    fontSize: 8,
    color: "#555555",
    fontFamily: "Helvetica-Bold",
  },
  paramValue: {
    fontSize: 8,
    color: "#333333",
  },
  // Bottleneck
  bottleneckBox: {
    backgroundColor: "#FFF4E5",
    borderLeftWidth: 3,
    borderLeftColor: "#E67E22",
    padding: 10,
    marginBottom: 12,
  },
  bottleneckText: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: "#333333",
    marginBottom: 4,
  },
  bottleneckSub: {
    fontSize: 8,
    color: "#555555",
  },
  // Risk score table
  riskTable: {
    marginBottom: 12,
  },
  riskTableHeader: {
    flexDirection: "row",
    backgroundColor: NAVY,
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  riskTableHeaderCell: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: "#FFFFFF",
  },
  riskTableRow: {
    flexDirection: "row",
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: "#E0E0E0",
  },
  riskTableRowAlt: {
    flexDirection: "row",
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: "#E0E0E0",
    backgroundColor: "#F8F9FA",
  },
  riskDomainCol: { width: "25%" },
  riskScoreCol: { width: "15%", textAlign: "center" },
  riskKeyCol: { width: "25%", textAlign: "right" },
  riskConfCol: { width: "35%", textAlign: "right" },
  scoreBadge: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: "#FFFFFF",
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 2,
  },
  bodyText: {
    fontSize: 8,
    color: "#444444",
    lineHeight: 1.5,
    marginBottom: 6,
  },
  // Detail sections
  domainSection: {
    marginBottom: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: "#E0E0E0",
    paddingBottom: 8,
  },
  domainHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  domainName: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: NAVY,
  },
  paramTable: {
    marginTop: 4,
    marginBottom: 4,
  },
  paramTableRow: {
    flexDirection: "row",
    paddingVertical: 2,
    borderBottomWidth: 0.5,
    borderBottomColor: "#F0F0F0",
  },
  paramTableLabel: {
    width: "55%",
    fontSize: 8,
    color: "#555555",
  },
  paramTableValue: {
    width: "45%",
    fontSize: 8,
    color: "#333333",
    textAlign: "right",
    fontFamily: "Courier",
  },
  mitigationBox: {
    backgroundColor: "#FFF8F0",
    borderLeftWidth: 2,
    borderLeftColor: "#E67E22",
    padding: 6,
    marginTop: 4,
  },
  mitigationLabel: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: "#999999",
    textTransform: "uppercase",
    marginBottom: 2,
  },
  mitigationText: {
    fontSize: 8,
    color: "#444444",
    lineHeight: 1.4,
  },
  // Projections table
  projTable: {
    marginBottom: 12,
  },
  projHeader: {
    flexDirection: "row",
    backgroundColor: NAVY,
    paddingVertical: 5,
    paddingHorizontal: 6,
  },
  projHeaderCell: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: "#FFFFFF",
  },
  projRow: {
    flexDirection: "row",
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: "#E0E0E0",
  },
  projRowAlt: {
    flexDirection: "row",
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: "#E0E0E0",
    backgroundColor: "#F8F9FA",
  },
  projParamCol: { width: "34%" },
  projValCol: { width: "22%", textAlign: "right", fontFamily: "Courier" },
  // Reliability
  reliabilityBox: {
    backgroundColor: "#F0F4F8",
    borderRadius: 4,
    padding: 10,
    marginBottom: 10,
  },
  scopeBox: {
    backgroundColor: "#FFF4E5",
    borderLeftWidth: 3,
    borderLeftColor: TEAL,
    padding: 10,
    marginTop: 8,
  },
  scopeText: {
    fontSize: 8,
    color: "#555555",
    lineHeight: 1.5,
    fontStyle: "italic",
  },
});

// --- Risk score colour indicator (text-based) ---

function ScoreBadge({ score }: { score: RiskScore }) {
  return (
    <Text style={[s.scoreBadge, { backgroundColor: RISK_COLOURS[score] }]}>
      {riskLabel(score)}
    </Text>
  );
}

// --- Footer component ---

function PageFooter() {
  return <Text style={s.footer}>{FOOTER_TEXT}</Text>;
}

// --- Header component ---

function PageHeader() {
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  return (
    <View style={s.headerBar}>
      <Text style={s.logoText}>Lemnisca</Text>
      <Text style={s.dateText}>{dateStr}</Text>
    </View>
  );
}

// --- Page 1: Executive Summary ---

function ExecutiveSummary({
  inputs,
  derived,
  results,
}: {
  inputs: ProcessInputs;
  derived: DerivedParameters;
  results: PartialAssessmentResult;
}) {
  const { otr, mixing, shear, co2, heat, primary_bottleneck: bottleneck } = results;
  const scaleRatio = inputs.v_target / inputs.v_lab;
  const species = SPECIES_LABELS[inputs.organism_species] ?? inputs.organism_species;
  const processType = PROCESS_TYPE_LABELS[inputs.process_type] ?? inputs.process_type;

  // Build summary paragraph
  const domains = [
    { name: "OTR", score: otr.score },
    { name: "Mixing", score: mixing.score },
    { name: "Shear", score: shear.score },
    { name: "CO\u2082", score: co2.score },
    { name: "Heat", score: heat.score },
  ];
  const highCrit = domains.filter(
    (d) => d.score === "high" || d.score === "critical",
  );
  const allLow = domains.every((d) => d.score === "low");

  let summaryParagraph: string;
  if (allLow) {
    summaryParagraph = `Scale-up from ${fmtInt(inputs.v_lab)} L to ${fmtInt(inputs.v_target)} L presents low risk across all five domains. Standard equipment and operating procedures are expected to maintain process performance at the target scale.`;
  } else if (highCrit.length === 0) {
    summaryParagraph = `Scale-up from ${fmtInt(inputs.v_lab)} L to ${fmtInt(inputs.v_target)} L presents moderate challenges. No critical constraints were identified. Standard scale-up procedures with attention to the flagged domains should be sufficient.`;
  } else {
    const names = highCrit.map((d) => d.name).join(", ");
    summaryParagraph = `Scale-up from ${fmtInt(inputs.v_lab)} L to ${fmtInt(inputs.v_target)} L presents ${highCrit.length === 1 ? "a significant" : "significant"} constraint${highCrit.length > 1 ? "s" : ""} in ${names}. ${bottleneck.statement} Targeted engineering intervention is recommended before proceeding to pilot scale.`;
  }

  const riskRows = [
    { domain: "Oxygen Transfer (OTR)", score: otr.score, key: `OTR/OUR: ${fmt(otr.kla_ratio, 2)}`, conf: confidenceLabel(otr.confidence) },
    { domain: "Mixing", score: mixing.score, key: mixing.da_max != null ? `\u03B8_mix: ${fmt(mixing.theta_mix_target)} s, Da: ${fmt(mixing.da_max, 3)}` : `\u03B8_mix: ${fmt(mixing.theta_mix_target)} s`, conf: confidenceLabel(mixing.confidence) },
    { domain: "Shear Stress", score: shear.score, key: `Tip speed: ${fmt(shear.tip_speed)} m/s`, conf: confidenceLabel(shear.confidence) },
    { domain: "CO\u2082 Accumulation", score: co2.score, key: co2.activated && co2.pco2_bottom != null ? `pCO\u2082: ${fmt(co2.pco2_bottom, 3)} bar` : "Not activated", conf: confidenceLabel(co2.confidence) },
    { domain: "Heat Removal", score: heat.score, key: `Heat ratio: ${fmt(heat.heat_ratio * 100)}%`, conf: confidenceLabel(heat.confidence) },
  ];

  return (
    <Page size="A4" style={s.page}>
      <PageHeader />

      <Text style={s.sectionTitle}>Executive Summary</Text>

      {/* Process parameters */}
      <View style={s.paramBox}>
        <View style={s.paramRow}>
          <Text style={s.paramLabel}>Organism</Text>
          <Text style={s.paramValue}>{species}</Text>
        </View>
        <View style={s.paramRow}>
          <Text style={s.paramLabel}>Process type</Text>
          <Text style={s.paramValue}>{processType}</Text>
        </View>
        <View style={s.paramRow}>
          <Text style={s.paramLabel}>Lab volume</Text>
          <Text style={s.paramValue}>{fmtInt(inputs.v_lab)} L</Text>
        </View>
        <View style={s.paramRow}>
          <Text style={s.paramLabel}>Target volume</Text>
          <Text style={s.paramValue}>{fmtInt(inputs.v_target)} L</Text>
        </View>
        <View style={s.paramRow}>
          <Text style={s.paramLabel}>Scale ratio</Text>
          <Text style={s.paramValue}>{fmt(scaleRatio, 0)}\u00D7</Text>
        </View>
      </View>

      {/* Primary bottleneck */}
      <View style={s.bottleneckBox}>
        <Text style={s.bottleneckText}>{bottleneck.statement}</Text>
        <Text style={s.bottleneckSub}>
          What would change this? {bottleneck.what_would_change}
        </Text>
      </View>

      {/* Risk score table */}
      <View style={s.riskTable}>
        <View style={s.riskTableHeader}>
          <Text style={[s.riskTableHeaderCell, s.riskDomainCol]}>Domain</Text>
          <Text style={[s.riskTableHeaderCell, s.riskScoreCol]}>Score</Text>
          <Text style={[s.riskTableHeaderCell, s.riskKeyCol]}>Key Metric</Text>
          <Text style={[s.riskTableHeaderCell, s.riskConfCol]}>Confidence</Text>
        </View>
        {riskRows.map((row, i) => (
          <View key={i} style={i % 2 === 0 ? s.riskTableRow : s.riskTableRowAlt}>
            <Text style={[{ fontSize: 8 }, s.riskDomainCol]}>{row.domain}</Text>
            <View style={[s.riskScoreCol, { alignItems: "center" }]}>
              <ScoreBadge score={row.score} />
            </View>
            <Text style={[{ fontSize: 8, fontFamily: "Courier" }, s.riskKeyCol]}>{row.key}</Text>
            <Text style={[{ fontSize: 7, color: "#666666" }, s.riskConfCol]}>{row.conf}</Text>
          </View>
        ))}
      </View>

      {/* Summary paragraph */}
      <Text style={s.bodyText}>{summaryParagraph}</Text>

      <PageFooter />
    </Page>
  );
}

// --- Page 2: Risk Assessment Detail ---

function RiskDetail({
  inputs,
  derived,
  results,
}: {
  inputs: ProcessInputs;
  derived: DerivedParameters;
  results: PartialAssessmentResult;
}) {
  const { otr, mixing, shear, co2, heat } = results;

  const domainSections: {
    id: string;
    name: string;
    score: RiskScore;
    confidence: Confidence;
    driver: string;
    params: { label: string; value: string }[];
    thresholdNote: string;
    uncertaintyNote: string;
  }[] = [
    {
      id: "otr",
      name: "Oxygen Transfer (OTR)",
      score: otr.score,
      confidence: otr.confidence,
      driver: otr.driver,
      params: [
        { label: "OUR peak", value: `${fmt(derived.our_peak)} mmol/L/h` },
        { label: "kLa required", value: `${fmt(otr.kla_required)} h\u207B\u00B9` },
        { label: "kLa achievable (moderate P/V)", value: `${fmt(otr.kla_target_moderate)} h\u207B\u00B9` },
        { label: "OTR/OUR ratio", value: fmt(otr.kla_ratio, 2) },
        { label: "P/V at target (moderate)", value: `${fmt(otr.pv_moderate)} W/m\u00B3` },
      ],
      thresholdNote: ">1.5 Low, 1.0\u20131.5 Moderate, 0.7\u20131.0 High, <0.7 Critical",
      uncertaintyNote: `kLa range: ${fmt(otr.kla_target_conservative)}\u2013${fmt(otr.kla_target_aggressive)} h\u207B\u00B9 (0.5\u00D7 to 2.0\u00D7 P/V)`,
    },
    {
      id: "mixing",
      name: "Mixing",
      score: mixing.score,
      confidence: mixing.confidence,
      driver: mixing.driver,
      params: [
        { label: "\u03B8_mix (lab)", value: `${fmt(mixing.theta_mix_lab)} s` },
        { label: "\u03B8_mix (target)", value: `${fmt(mixing.theta_mix_target)} s` },
        ...(mixing.da_max != null
          ? [{ label: "Da (Damk\u00F6hler number)", value: fmt(mixing.da_max, 3) }]
          : []),
      ],
      thresholdNote: mixing.da_max != null
        ? "Da: <0.01 Low, 0.01\u20130.1 Moderate, 0.1\u20131.0 High, >1.0 Critical"
        : "\u03B8_mix: <30s Low, 30\u201360s Moderate, >60s High",
      uncertaintyNote: `Mixing time scales as (V_target/V_lab)^(1/3). Actual performance depends on vessel internals and impeller configuration.`,
    },
    {
      id: "shear",
      name: "Shear Stress",
      score: shear.score,
      confidence: shear.confidence,
      driver: shear.driver,
      params: [
        { label: "Tip speed (target)", value: `${fmt(shear.tip_speed)} m/s` },
        { label: "Organism threshold", value: `${fmt(shear.tip_speed_threshold)} m/s` },
        { label: "Tip speed ratio", value: fmt(shear.tip_speed_ratio, 2) },
      ],
      thresholdNote: "<0.7 Low, 0.7\u20131.0 Moderate, 1.0\u20131.3 High, >1.3 Critical",
      uncertaintyNote: `Based on constant P/V scaling. Constant tip speed scaling would yield different results.`,
    },
    {
      id: "co2",
      name: "CO\u2082 Accumulation",
      score: co2.score,
      confidence: co2.confidence,
      driver: co2.driver,
      params: co2.activated
        ? [
            { label: "CER", value: `${fmt(co2.cer ?? 0)} mmol/L/h` },
            { label: "kLa_CO\u2082", value: `${fmt(co2.kla_co2 ?? 0)} h\u207B\u00B9` },
            { label: "pCO\u2082 bulk", value: `${fmt(co2.pco2_bulk ?? 0, 3)} bar` },
            { label: "pCO\u2082 bottom", value: `${fmt(co2.pco2_bottom ?? 0, 3)} bar` },
          ]
        : [{ label: "Status", value: "Not activated (below biomass/OUR thresholds)" }],
      thresholdNote: "<0.08 bar Low, 0.08\u20130.15 Moderate, 0.15\u20130.25 High, >0.25 Critical",
      uncertaintyNote: `CO\u2082 carries the widest confidence interval of the five domains. Simplified mass balance model.`,
    },
    {
      id: "heat",
      name: "Heat Removal",
      score: heat.score,
      confidence: heat.confidence,
      driver: heat.driver,
      params: [
        { label: "Q_metabolic", value: `${fmt(heat.q_metabolic, 2)} kW` },
        { label: "Q_cool_max", value: `${fmt(heat.q_cool_max, 2)} kW` },
        { label: "Heat ratio", value: fmt(heat.heat_ratio, 2) },
        { label: "A_jacket", value: `${fmt(heat.a_jacket, 2)} m\u00B2` },
        { label: "\u0394T_lm", value: `${fmt(heat.dt_lm, 1)}\u00B0C` },
      ],
      thresholdNote: "<0.60 Low, 0.60\u20130.85 Moderate, 0.85\u20131.00 High, >1.00 Critical",
      uncertaintyNote: `Assumes U = 400 W/m\u00B2\u00B7K and cooling water outlet T_cw_in + 10\u00B0C. Internal coils not modelled.`,
    },
  ];

  return (
    <Page size="A4" style={s.page}>
      <PageHeader />
      <Text style={s.sectionTitle}>Risk Assessment Detail</Text>

      {domainSections.map((section) => {
        const mitigation = getMitigation(section.id, results, inputs);
        return (
          <View key={section.id} style={s.domainSection} wrap={false}>
            <View style={s.domainHeader}>
              <Text style={s.domainName}>{section.name}</Text>
              <ScoreBadge score={section.score} />
            </View>

            {/* Key params */}
            <View style={s.paramTable}>
              {section.params.map((p, i) => (
                <View key={i} style={s.paramTableRow}>
                  <Text style={s.paramTableLabel}>{p.label}</Text>
                  <Text style={s.paramTableValue}>{p.value}</Text>
                </View>
              ))}
            </View>

            {/* Threshold */}
            <Text style={{ fontSize: 7, color: "#888888", marginBottom: 2 }}>
              Thresholds: {section.thresholdNote}
            </Text>

            {/* Uncertainty */}
            <Text style={{ fontSize: 7, color: "#888888", marginBottom: 2 }}>
              Uncertainty: {section.uncertaintyNote}
            </Text>

            {/* Confidence */}
            <Text style={{ fontSize: 7, color: "#888888" }}>
              Confidence: {confidenceLabel(section.confidence)} \u2014 {section.driver}
            </Text>

            {/* Mitigation */}
            {mitigation && (
              <View style={s.mitigationBox}>
                <Text style={s.mitigationLabel}>Mitigation Recommendation</Text>
                <Text style={s.mitigationText}>{mitigation}</Text>
              </View>
            )}
          </View>
        );
      })}

      <PageFooter />
    </Page>
  );
}

// --- Page 3: Quantitative Projections ---

function Projections({
  inputs,
  derived,
  results,
}: {
  inputs: ProcessInputs;
  derived: DerivedParameters;
  results: PartialAssessmentResult;
}) {
  const { otr, mixing, shear, co2, heat } = results;
  const vPilot = pilotVolume(inputs.v_lab, inputs.v_target);
  const pilot = computePilot(inputs, derived);

  const labTipSpeed = Math.PI * derived.n_rps * derived.lab_geometry.d_imp;
  const heatKwM3Lab = METABOLIC_HEAT_FACTOR * derived.our_peak;
  const heatKwM3Target =
    derived.target_geometry.volume_m3 > 0
      ? heat.q_metabolic / derived.target_geometry.volume_m3
      : 0;

  const rows: { param: string; lab: string; pilotVal: string; prod: string }[] = [
    {
      param: "kLa achievable (h\u207B\u00B9)",
      lab: fmt(otr.kla_lab),
      pilotVal: fmt(pilot.klaAchievable),
      prod: fmt(otr.kla_target_moderate),
    },
    {
      param: "kLa required (h\u207B\u00B9)",
      lab: fmt(otr.kla_required),
      pilotVal: fmt(otr.kla_required),
      prod: fmt(otr.kla_required),
    },
    {
      param: "Mixing time (s)",
      lab: fmt(mixing.theta_mix_lab),
      pilotVal: fmt(pilot.mixingTime),
      prod: fmt(mixing.theta_mix_target),
    },
    {
      param: "Da (mixing)",
      lab: "\u2014",
      pilotVal: pilot.da_max != null ? fmt(pilot.da_max, 3) : "\u2014",
      prod: mixing.da_max != null ? fmt(mixing.da_max, 3) : "\u2014",
    },
    {
      param: "Tip speed (m/s)",
      lab: fmt(labTipSpeed),
      pilotVal: fmt(pilot.tipSpeed),
      prod: fmt(shear.tip_speed),
    },
    {
      param: "pCO\u2082 bottom (bar)",
      lab: "\u2014",
      pilotVal: pilot.pco2Bottom != null ? fmt(pilot.pco2Bottom, 3) : "\u2014",
      prod: co2.pco2_bottom != null ? fmt(co2.pco2_bottom, 3) : "\u2014",
    },
    {
      param: "Metabolic heat (kW/m\u00B3)",
      lab: fmt(heatKwM3Lab, 2),
      pilotVal: fmt(pilot.heatKwM3, 2),
      prod: fmt(heatKwM3Target, 2),
    },
  ];

  return (
    <Page size="A4" style={s.page}>
      <PageHeader />
      <Text style={s.sectionTitle}>Quantitative Projections</Text>

      <Text style={s.bodyText}>
        Projections across three scales: lab ({fmtInt(inputs.v_lab)} L), pilot ({fmtInt(vPilot)} L, geometric mean), and production ({fmtInt(inputs.v_target)} L). All values computed at constant P/V (moderate scenario, 1.0\u00D7).
      </Text>

      <View style={s.projTable}>
        <View style={s.projHeader}>
          <Text style={[s.projHeaderCell, s.projParamCol]}>Parameter</Text>
          <Text style={[s.projHeaderCell, s.projValCol]}>
            Lab ({fmtInt(inputs.v_lab)} L)
          </Text>
          <Text style={[s.projHeaderCell, s.projValCol]}>
            Pilot ({fmtInt(vPilot)} L)
          </Text>
          <Text style={[s.projHeaderCell, s.projValCol]}>
            Production ({fmtInt(inputs.v_target)} L)
          </Text>
        </View>
        {rows.map((row, i) => (
          <View key={i} style={i % 2 === 0 ? s.projRow : s.projRowAlt}>
            <Text style={[{ fontSize: 8 }, s.projParamCol]}>{row.param}</Text>
            <Text style={[{ fontSize: 8, fontFamily: "Courier" }, s.projValCol]}>
              {row.lab}
            </Text>
            <Text style={[{ fontSize: 8, fontFamily: "Courier" }, s.projValCol]}>
              {row.pilotVal}
            </Text>
            <Text style={[{ fontSize: 8, fontFamily: "Courier" }, s.projValCol]}>
              {row.prod}
            </Text>
          </View>
        ))}
      </View>

      {/* Additional context */}
      <Text style={s.subsectionTitle}>Scale-Up Basis</Text>
      <View style={s.paramTable}>
        <View style={s.paramTableRow}>
          <Text style={s.paramTableLabel}>Scale-up rule</Text>
          <Text style={s.paramTableValue}>Constant P/V</Text>
        </View>
        <View style={s.paramTableRow}>
          <Text style={s.paramTableLabel}>P/V (lab)</Text>
          <Text style={s.paramTableValue}>{fmt(derived.pv_lab)} W/m{"\u00B3"}</Text>
        </View>
        <View style={s.paramTableRow}>
          <Text style={s.paramTableLabel}>Impeller type</Text>
          <Text style={s.paramTableValue}>{inputs.impeller_type}</Text>
        </View>
        <View style={s.paramTableRow}>
          <Text style={s.paramTableLabel}>H/D (target)</Text>
          <Text style={s.paramTableValue}>{fmt(inputs.h_d_target, 1)}</Text>
        </View>
        <View style={s.paramTableRow}>
          <Text style={s.paramTableLabel}>Impellers (target)</Text>
          <Text style={s.paramTableValue}>{inputs.n_impellers}</Text>
        </View>
        <View style={s.paramTableRow}>
          <Text style={s.paramTableLabel}>VVM</Text>
          <Text style={s.paramTableValue}>{fmt(inputs.vvm, 1)}</Text>
        </View>
      </View>

      <PageFooter />
    </Page>
  );
}

// --- Page 4: Reliability Statement ---

function ReliabilityStatement({
  inputs,
  derived,
  results,
}: {
  inputs: ProcessInputs;
  derived: DerivedParameters;
  results: PartialAssessmentResult;
}) {
  const { provided, estimated, total } = countEstimatedParams(inputs);
  const assumptions = getHighImpactAssumptions(inputs, derived, results);
  const measurementAdvice = getSingleMeasurementAdvice(inputs);

  return (
    <Page size="A4" style={s.page}>
      <PageHeader />
      <Text style={s.sectionTitle}>Reliability Statement</Text>

      {/* Input provenance */}
      <Text style={s.subsectionTitle}>Input Provenance</Text>
      <View style={s.reliabilityBox}>
        <View style={s.paramRow}>
          <Text style={s.paramLabel}>Parameters provided</Text>
          <Text style={s.paramValue}>{provided} of {total}</Text>
        </View>
        <View style={s.paramRow}>
          <Text style={s.paramLabel}>Parameters estimated</Text>
          <Text style={s.paramValue}>{estimated} of {total}</Text>
        </View>
        <View style={s.paramRow}>
          <Text style={s.paramLabel}>OUR source</Text>
          <Text style={s.paramValue}>
            {inputs.our_mode === "measured"
              ? "User-provided measurement"
              : inputs.our_mode === "exhaust_gas"
                ? "Derived from exhaust gas analysis"
                : "Estimated from literature"}
          </Text>
        </View>
      </View>

      {/* High-impact assumptions */}
      <Text style={s.subsectionTitle}>Highest-Impact Assumptions</Text>
      {assumptions.map((a, i) => (
        <View key={i} style={{ flexDirection: "row", marginBottom: 4 }}>
          <Text style={{ fontSize: 8, color: TEAL, marginRight: 4 }}>{i + 1}.</Text>
          <Text style={[s.bodyText, { flex: 1, marginBottom: 0 }]}>{a}</Text>
        </View>
      ))}

      {/* Single measurement */}
      <Text style={[s.subsectionTitle, { marginTop: 12 }]}>
        Most Valuable Additional Measurement
      </Text>
      <Text style={s.bodyText}>{measurementAdvice}</Text>

      {/* Scope limitation */}
      <View style={s.scopeBox}>
        <Text style={[s.subsectionTitle, { color: NAVY, marginTop: 0 }]}>
          Scope Limitation
        </Text>
        <Text style={s.scopeText}>
          This assessment is based on empirical correlations with {"\u00B1"}30{"\u2013"}40% uncertainty on kLa. It does not predict yield or replace pilot experimentation.
        </Text>
      </View>

      <PageFooter />
    </Page>
  );
}

// --- Main document ---

export interface PdfReportProps {
  inputs: ProcessInputs;
  derived: DerivedParameters;
  results: PartialAssessmentResult;
}

export function PdfReportDocument({ inputs, derived, results }: PdfReportProps) {
  return (
    <Document
      title="Lemnisca Scale-Up Risk Assessment"
      author="Lemnisca Fermentation Scale-Up Risk Predictor"
    >
      <ExecutiveSummary inputs={inputs} derived={derived} results={results} />
      <RiskDetail inputs={inputs} derived={derived} results={results} />
      <Projections inputs={inputs} derived={derived} results={results} />
      <ReliabilityStatement inputs={inputs} derived={derived} results={results} />
    </Document>
  );
}
