// Four-page PDF report. Built with @react-pdf/renderer — these aren't
// HTML primitives, they're the library's own Document/Page/View/Text
// elements rendered through its layout engine.
//
// Imported lazily by GeneratePdfButton (the library pulls in pdfkit + a
// chunk of Buffer polyfills, so the runtime cost is meaningful — keep it
// off the main bundle).

import {
  Document,
  Page,
  View,
  Text,
  StyleSheet,
} from '@react-pdf/renderer';
import type {
  ProcessInputs,
  PartialAssessmentResult,
  RiskScore,
  Confidence,
} from '@torch/core';
import { speciesLabel } from '../format';

const NAVY  = '#1B3A5C';
const TEAL  = '#0D7377';
const FOG   = '#F0F4F8';
const RULE  = '#D7DEE6';
const INK   = '#1a2536';
const MUTED = '#5a6e82';
const WARN  = '#C2410C';

const RISK_HEX: Record<RiskScore, string> = {
  low:      '#059669',
  moderate: '#B45309',
  high:     '#C2410C',
  critical: '#DC2626',
};

const RISK_LABEL: Record<RiskScore, string> = {
  low: 'Low',
  moderate: 'Moderate',
  high: 'High',
  critical: 'Critical',
};

const CONF_LABEL: Record<Confidence, string> = {
  high_confidence: 'High confidence',
  reliable: 'Reliable',
  directional: 'Directional',
};

const s = StyleSheet.create({
  page: { paddingTop: 36, paddingBottom: 40, paddingHorizontal: 42, fontSize: 9, color: INK, fontFamily: 'Helvetica' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 18, paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: RULE, borderBottomStyle: 'solid' },
  brand: { fontSize: 12, fontWeight: 700, color: NAVY, letterSpacing: 0.5 },
  meta: { fontSize: 7, color: MUTED },
  sectionTitle: { fontSize: 14, fontWeight: 700, color: NAVY, marginBottom: 12 },
  subTitle: { fontSize: 10, fontWeight: 700, color: TEAL, marginTop: 14, marginBottom: 6 },
  paragraph: { fontSize: 9, lineHeight: 1.45, color: INK, marginBottom: 6 },
  small: { fontSize: 8, color: MUTED },
  monoValue: { fontFamily: 'Courier', color: INK },
  footer: { position: 'absolute', bottom: 22, left: 42, right: 42, paddingTop: 6, borderTopWidth: 1, borderTopColor: RULE, borderTopStyle: 'solid', fontSize: 7, color: MUTED },

  paramBox: { backgroundColor: FOG, padding: 10, borderRadius: 4 },
  paramRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 3 },

  bottleneckBox: { padding: 10, borderLeftWidth: 3, borderLeftColor: WARN, borderLeftStyle: 'solid', backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: RULE, borderStyle: 'solid', borderRadius: 2, marginTop: 12, marginBottom: 14 },

  mitigationBox: { marginTop: 6, padding: 8, borderLeftWidth: 3, borderLeftColor: WARN, borderLeftStyle: 'solid', backgroundColor: '#FFF8F2' },

  table: { width: '100%', marginTop: 6 },
  th: { flexDirection: 'row', backgroundColor: NAVY, paddingVertical: 5, paddingHorizontal: 8 },
  thText: { color: '#FFFFFF', fontSize: 8, fontWeight: 700 },
  tr: { flexDirection: 'row', paddingVertical: 5, paddingHorizontal: 8, borderBottomWidth: 0.5, borderBottomColor: RULE, borderBottomStyle: 'solid' },
  trAlt: { backgroundColor: FOG },
  td: { fontSize: 9, color: INK },

  badge: { paddingHorizontal: 5, paddingVertical: 1, borderRadius: 8, fontSize: 8, fontWeight: 700 },

  scopeBox: { marginTop: 14, padding: 10, borderLeftWidth: 3, borderLeftColor: TEAL, borderLeftStyle: 'solid', backgroundColor: '#F0F8F8', borderRadius: 2 },
});

type Props = { inputs: ProcessInputs; results: PartialAssessmentResult };

function fmt(n: number | undefined, digits = 2, unit = '') {
  if (n === undefined || !Number.isFinite(n)) return '—';
  return `${n.toFixed(digits)}${unit ? ` ${unit}` : ''}`;
}

function PageFrame({ children }: { children: React.ReactNode }) {
  const date = new Date().toISOString().slice(0, 10);
  return (
    <Page size="A4" style={s.page}>
      <View style={s.header}>
        <Text style={s.brand}>LEMNISCA · TORCH</Text>
        <Text style={s.meta}>Scale-up risk assessment · {date}</Text>
      </View>
      {children}
      <Text style={s.footer} fixed>
        Generated by Lemnisca Torch. Predictions are bounded by empirical correlations (±30–40% on kLa) and do not replace pilot experimentation.
      </Text>
    </Page>
  );
}

function Badge({ score }: { score: RiskScore }) {
  return (
    <Text style={[s.badge, { color: RISK_HEX[score], borderWidth: 1, borderColor: RISK_HEX[score], borderStyle: 'solid' }]}>
      {RISK_LABEL[score]}
    </Text>
  );
}

// ─── Page 1: Executive Summary ───────────────────────────────────────────────

function ExecutiveSummary({ inputs, results }: Props) {
  const bn = results.primary_bottleneck;
  const rows: { domain: string; score: RiskScore; metric: string; confidence: Confidence }[] = [
    { domain: 'Oxygen transfer',  score: results.otr.score,    metric: `OTR/OUR ${fmt(results.otr.otr_our_ratio_target ?? results.otr.kla_ratio, 2)}`, confidence: results.otr.confidence },
    { domain: 'Mixing',           score: results.mixing.score, metric: `τ_mix ${fmt(results.mixing.theta_mix_target, 1, 's')}`, confidence: results.mixing.confidence },
    { domain: 'Shear stress',     score: results.shear.score,  metric: `v_tip ${fmt(results.shear.tip_speed, 2, 'm/s')}`, confidence: results.shear.confidence },
    { domain: 'CO₂ accumulation', score: results.co2.score,    metric: results.co2.activated ? `pCO₂_bot ${fmt(results.co2.target?.pco2_bottom ?? results.co2.pco2_bottom, 3, 'bar')}` : 'Not activated', confidence: results.co2.confidence },
    { domain: 'Heat removal',     score: results.heat.score,   metric: `Q ${fmt(results.heat.q_cool_max, 1)}/${fmt(results.heat.q_metabolic, 1, 'kW')}`, confidence: results.heat.confidence },
  ];
  return (
    <PageFrame>
      <Text style={s.sectionTitle}>Executive Summary</Text>

      <View style={s.paramBox}>
        <View style={s.paramRow}><Text>Organism</Text><Text style={s.monoValue}>{speciesLabel(inputs.organism_species)}</Text></View>
        <View style={s.paramRow}><Text>Lab volume</Text><Text style={s.monoValue}>{inputs.v_lab} L</Text></View>
        <View style={s.paramRow}><Text>Target volume</Text><Text style={s.monoValue}>{inputs.v_target} L</Text></View>
        <View style={s.paramRow}><Text>Scale ratio</Text><Text style={s.monoValue}>{(inputs.v_target / inputs.v_lab).toFixed(0)}×</Text></View>
        <View style={s.paramRow}><Text>Scale-up criterion</Text><Text style={s.monoValue}>{(inputs.scaleup_criterion ?? 'power_per_volume').replace(/_/g, ' ')}</Text></View>
      </View>

      <View style={s.bottleneckBox}>
        <Text style={{ fontSize: 8, fontWeight: 700, color: WARN, marginBottom: 4 }}>PRIMARY BOTTLENECK</Text>
        <Text style={s.paragraph}>
          {bn.domain ? bn.statement : 'No domain reached the moderate threshold at target scale.'}
        </Text>
      </View>

      <Text style={s.subTitle}>Domain summary</Text>
      <View style={s.table}>
        <View style={s.th}>
          <Text style={[s.thText, { width: '32%' }]}>Domain</Text>
          <Text style={[s.thText, { width: '18%' }]}>Score</Text>
          <Text style={[s.thText, { width: '30%' }]}>Key metric</Text>
          <Text style={[s.thText, { width: '20%' }]}>Confidence</Text>
        </View>
        {rows.map((r, i) => (
          <View key={r.domain} style={[s.tr, i % 2 === 1 ? s.trAlt : {}]}>
            <Text style={[s.td, { width: '32%' }]}>{r.domain}</Text>
            <View style={{ width: '18%' }}><Badge score={r.score} /></View>
            <Text style={[s.td, s.monoValue, { width: '30%' }]}>{r.metric}</Text>
            <Text style={[s.td, { width: '20%' }]}>{CONF_LABEL[r.confidence]}</Text>
          </View>
        ))}
      </View>
    </PageFrame>
  );
}

// ─── Page 2: Risk Detail ─────────────────────────────────────────────────────

function RiskDetail({ inputs, results }: Props) {
  type DomainBlock = {
    title: string;
    score: RiskScore;
    confidence: Confidence;
    driver: string;
    params: { label: string; value: string }[];
    thresholds: string;
    mitigation?: string;
  };

  const blocks: DomainBlock[] = [
    {
      title: 'Oxygen transfer',
      score: results.otr.score,
      confidence: results.otr.confidence,
      driver: results.otr.driver,
      params: [
        { label: 'kLa achievable (target)', value: fmt(results.otr.kla_target_moderate, 1, 'h⁻¹') },
        { label: 'kLa required',           value: fmt(results.otr.kla_required, 1, 'h⁻¹') },
        { label: 'OTR/OUR (target)',       value: fmt(results.otr.otr_our_ratio_target ?? results.otr.kla_ratio, 2) },
        { label: 'P/V (target)',           value: fmt(results.otr.pv_target, 0, 'W/m³') },
      ],
      thresholds: 'Low > 1.5 · Moderate 1.0–1.5 · High 0.7–1.0 · Critical < 0.7',
      mitigation: results.otr.score === 'high' || results.otr.score === 'critical'
        ? 'Increase RPM (within tip-speed bound), raise O₂ enrichment, or add baffles to push kLa upward.'
        : undefined,
    },
    {
      title: 'Mixing',
      score: results.mixing.score,
      confidence: results.mixing.confidence,
      driver: results.mixing.driver,
      params: [
        { label: 'τ_mix (target)',     value: fmt(results.mixing.theta_mix_target, 1, 's') },
        { label: 'τ_process',          value: fmt(results.mixing.t_process_target_s, 1, 's') },
        { label: 'Process/mix margin', value: fmt(results.mixing.process_mixing_ratio_target, 2) },
      ],
      thresholds: 'Low > 10 · Moderate 1–10 · High 0.1–1 · Critical < 0.1',
      mitigation: results.mixing.score === 'high' || results.mixing.score === 'critical'
        ? 'Use multiple impellers, increase impeller diameter (within D/T 0.4), or reduce feed pulsing frequency.'
        : undefined,
    },
    {
      title: 'Shear stress',
      score: results.shear.score,
      confidence: results.shear.confidence,
      driver: results.shear.driver,
      params: [
        { label: 'Tip speed (target)', value: fmt(results.shear.tip_speed, 2, 'm/s') },
        { label: 'Threshold',          value: fmt(results.shear.tip_speed_threshold, 2, 'm/s') },
        { label: 'Margin',             value: fmt(results.shear.tip_speed_margin, 2) },
      ],
      thresholds: 'Low > 1.43 · Moderate 1.0–1.43 · High 0.77–1.0 · Critical < 0.77',
      mitigation: results.shear.score === 'high' || results.shear.score === 'critical'
        ? 'Switch to lower-shear impeller (pitched-blade or marine), reduce RPM, or scale by tip-speed criterion.'
        : undefined,
    },
    {
      title: 'CO₂ accumulation',
      score: results.co2.score,
      confidence: results.co2.confidence,
      driver: results.co2.driver,
      params: results.co2.activated
        ? [
            { label: 'pCO₂ at bottom',  value: fmt(results.co2.target?.pco2_bottom ?? results.co2.pco2_bottom, 3, 'bar') },
            { label: 'pCO₂ threshold',  value: fmt(results.co2.pco2_critical, 3, 'bar') },
            { label: 'Margin',          value: fmt(results.co2.pco2_margin, 2) },
          ]
        : [{ label: 'Status', value: 'Not activated (low OUR)' }],
      thresholds: 'Low > 1.5 · Moderate 1.0–1.5 · High 0.75–1.0 · Critical < 0.75',
      mitigation: (results.co2.score === 'high' || results.co2.score === 'critical')
        ? 'Increase aeration (VVM), use a tall narrow geometry, or reduce vessel depth via a wider H/D.'
        : undefined,
    },
    {
      title: 'Heat removal',
      score: results.heat.score,
      confidence: results.heat.confidence,
      driver: results.heat.driver,
      params: [
        { label: 'Q_metabolic',        value: fmt(results.heat.q_metabolic, 1, 'kW') },
        { label: 'Q_cooling_max',      value: fmt(results.heat.q_cool_max, 1, 'kW') },
        { label: 'Margin',             value: fmt(results.heat.heat_transfer_margin, 2) },
        { label: 'Jacket area',        value: fmt(results.heat.a_jacket, 2, 'm²') },
      ],
      thresholds: 'Low > 1.67 · Moderate 1.18–1.67 · High 1.0–1.18 · Critical < 1.0',
      mitigation: results.heat.score === 'high' || results.heat.score === 'critical'
        ? 'Add internal cooling coils, drop CW inlet temperature, or accept reduced peak biomass.'
        : undefined,
    },
  ];

  return (
    <PageFrame>
      <Text style={s.sectionTitle}>Risk Detail</Text>
      <Text style={s.small}>
        Inputs: {speciesLabel(inputs.organism_species)} · {inputs.v_lab}→{inputs.v_target} L · {(inputs.scaleup_criterion ?? 'power_per_volume').replace(/_/g, ' ')}
      </Text>

      {blocks.map((b) => (
        <View key={b.title} wrap={false} style={{ marginTop: 12 }}>
          <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 }}>
            <Text style={{ fontSize: 11, fontWeight: 700, color: NAVY }}>{b.title}</Text>
            <Badge score={b.score} />
          </View>
          <View style={s.paramBox}>
            {b.params.map((p) => (
              <View key={p.label} style={s.paramRow}>
                <Text>{p.label}</Text>
                <Text style={s.monoValue}>{p.value}</Text>
              </View>
            ))}
          </View>
          <Text style={[s.small, { marginTop: 4 }]}>Thresholds: {b.thresholds}</Text>
          <Text style={[s.small, { marginTop: 2 }]}>Confidence: {CONF_LABEL[b.confidence]} — {b.driver}</Text>
          {b.mitigation ? (
            <View style={s.mitigationBox}>
              <Text style={{ fontSize: 8, fontWeight: 700, color: WARN, marginBottom: 2 }}>Mitigation</Text>
              <Text style={s.paragraph}>{b.mitigation}</Text>
            </View>
          ) : null}
        </View>
      ))}
    </PageFrame>
  );
}

// ─── Page 3: Quantitative Projections ────────────────────────────────────────

function Projections({ inputs, results }: Props) {
  const rows: { label: string; lab: string; target: string }[] = [
    { label: 'kLa (h⁻¹)',           lab: fmt(results.otr.kla_lab, 1),                                            target: fmt(results.otr.kla_target_moderate, 1) },
    { label: 'kLa required (h⁻¹)',  lab: fmt(results.otr.kla_required, 1),                                       target: fmt(results.otr.kla_required, 1) },
    { label: 'Mixing time (s)',     lab: fmt(results.mixing.theta_mix_lab, 1),                                   target: fmt(results.mixing.theta_mix_target, 1) },
    { label: 'Mixing margin',       lab: fmt(results.mixing.process_mixing_ratio_lab, 2),                        target: fmt(results.mixing.process_mixing_ratio_target, 2) },
    { label: 'Tip speed (m/s)',     lab: fmt(results.shear.tip_speed_lab, 2),                                    target: fmt(results.shear.tip_speed, 2) },
    { label: 'pCO₂ at bottom (bar)', lab: results.co2.activated ? fmt(results.co2.lab?.pco2_bottom, 3) : '—',     target: results.co2.activated ? fmt(results.co2.target?.pco2_bottom ?? results.co2.pco2_bottom, 3) : '—' },
    { label: 'Metabolic heat (kW)', lab: fmt(results.heat.lab?.q_metabolic, 2),                                  target: fmt(results.heat.target?.q_metabolic ?? results.heat.q_metabolic, 2) },
    { label: 'Cooling capacity (kW)', lab: fmt(results.heat.lab?.q_cool_max, 2),                                 target: fmt(results.heat.target?.q_cool_max ?? results.heat.q_cool_max, 2) },
  ];

  return (
    <PageFrame>
      <Text style={s.sectionTitle}>Quantitative Projections</Text>
      <Text style={s.paragraph}>
        Side-by-side comparison of every key derived quantity at the two scales the assessment evaluated.
      </Text>

      <View style={[s.table, { marginTop: 8 }]}>
        <View style={s.th}>
          <Text style={[s.thText, { width: '50%' }]}>Quantity</Text>
          <Text style={[s.thText, { width: '25%', textAlign: 'right' }]}>{`Lab (${inputs.v_lab} L)`}</Text>
          <Text style={[s.thText, { width: '25%', textAlign: 'right' }]}>{`Target (${inputs.v_target} L)`}</Text>
        </View>
        {rows.map((r, i) => (
          <View key={r.label} style={[s.tr, i % 2 === 1 ? s.trAlt : {}]}>
            <Text style={[s.td, { width: '50%' }]}>{r.label}</Text>
            <Text style={[s.td, s.monoValue, { width: '25%', textAlign: 'right' }]}>{r.lab}</Text>
            <Text style={[s.td, s.monoValue, { width: '25%', textAlign: 'right' }]}>{r.target}</Text>
          </View>
        ))}
      </View>

      <Text style={s.subTitle}>Scale-up basis</Text>
      <View style={s.paramBox}>
        <View style={s.paramRow}><Text>Criterion</Text><Text style={s.monoValue}>{(inputs.scaleup_criterion ?? 'power_per_volume').replace(/_/g, ' ')}</Text></View>
        <View style={s.paramRow}><Text>Impeller type</Text><Text style={s.monoValue}>{inputs.impeller_type.replace('_', '-')}</Text></View>
        <View style={s.paramRow}><Text>Impellers (lab / target)</Text><Text style={s.monoValue}>{inputs.n_impellers} / {inputs.n_impellers_target ?? inputs.n_impellers}</Text></View>
        <View style={s.paramRow}><Text>H/D (lab / target)</Text><Text style={s.monoValue}>{inputs.h_d_lab.toFixed(2)} / {inputs.h_d_target.toFixed(2)}</Text></View>
        <View style={s.paramRow}><Text>VVM</Text><Text style={s.monoValue}>{inputs.vvm.toFixed(2)}</Text></View>
      </View>
    </PageFrame>
  );
}

// ─── Page 4: Reliability Statement ───────────────────────────────────────────

function Reliability({ inputs, results }: Props) {
  const ourMeasured = inputs.our_mode === 'measured';
  const provenance = [
    { label: 'Organism + species', value: 'User-provided' },
    { label: 'Scale (lab / target)', value: 'User-provided' },
    { label: 'Geometry (H/D, D/T, impeller)', value: 'User-provided with sensible defaults' },
    { label: 'Operating (RPM, VVM, DO)', value: 'User-provided with defaults where omitted' },
    { label: 'OUR (peak)', value: ourMeasured ? 'User-measured (high confidence)' : 'Estimated from literature kinetics' },
    { label: 'Temperature + cooling water', value: 'User-provided' },
  ];

  const assumptions = [
    'kLa estimated via the van\'t Riet ensemble for coalescing/non-coalescing media; ±30–40% intrinsic uncertainty.',
    inputs.impeller_type === 'unknown'
      ? 'Unknown impeller type treated as Rushton geometry — replace with actual type for sharper power and shear estimates.'
      : 'Mixing time blended across Ruszkowski, Cooke, and Grenville-Nienow ensembles.',
    ourMeasured
      ? 'OUR is user-measured; downstream margins inherit this directly.'
      : 'OUR estimated from biomass + species — a measured value would tighten every domain except shear.',
  ];

  const recommendation = ourMeasured
    ? 'Pilot kLa measurement at intermediate volume to validate the scale-up envelope.'
    : 'A direct OUR measurement at peak biomass is the single highest-leverage measurement to upgrade this report.';

  return (
    <PageFrame>
      <Text style={s.sectionTitle}>Reliability Statement</Text>

      <Text style={s.subTitle}>Input provenance</Text>
      <View style={s.paramBox}>
        {provenance.map((p) => (
          <View key={p.label} style={s.paramRow}>
            <Text>{p.label}</Text>
            <Text style={s.monoValue}>{p.value}</Text>
          </View>
        ))}
      </View>

      <Text style={s.subTitle}>Highest-impact assumptions</Text>
      {assumptions.map((a, i) => (
        <View key={i} style={{ flexDirection: 'row', marginBottom: 4 }}>
          <Text style={{ width: 16, color: TEAL, fontWeight: 700 }}>{i + 1}.</Text>
          <Text style={[s.paragraph, { flex: 1 }]}>{a}</Text>
        </View>
      ))}

      <Text style={s.subTitle}>Most valuable additional measurement</Text>
      <Text style={s.paragraph}>{recommendation}</Text>

      <View style={s.scopeBox}>
        <Text style={{ fontSize: 8, fontWeight: 700, color: TEAL, marginBottom: 3 }}>SCOPE LIMITATIONS</Text>
        <Text style={s.paragraph}>
          This assessment is based on empirical correlations with ±30–40% uncertainty on kLa and ±15–20% on heat transfer. It does not predict yield, product titer, or replace pilot experimentation. Risk categories indicate the magnitude of attention each domain needs, not absolute pass/fail.
        </Text>
      </View>

      <View style={{ marginTop: 16, paddingTop: 8, borderTopWidth: 0.5, borderTopColor: RULE, borderTopStyle: 'solid' }}>
        <Text style={s.small}>
          Inputs: {speciesLabel(inputs.organism_species)} · {inputs.process_type.replace('_', '-')} · {inputs.v_lab} L → {inputs.v_target} L · {ourMeasured ? `measured OUR ${fmt(inputs.our_measured, 0, 'mmol/L/h')}` : 'estimated OUR'}
        </Text>
      </View>
    </PageFrame>
  );
}

export function PdfReportDocument({ inputs, results }: Props) {
  return (
    <Document
      title={`Lemnisca Torch — ${speciesLabel(inputs.organism_species)} ${inputs.v_lab}→${inputs.v_target} L`}
      author="Lemnisca Torch"
      creator="Lemnisca Torch"
      producer="@react-pdf/renderer"
    >
      <ExecutiveSummary inputs={inputs} results={results} />
      <RiskDetail       inputs={inputs} results={results} />
      <Projections      inputs={inputs} results={results} />
      <Reliability      inputs={inputs} results={results} />
    </Document>
  );
}
